/*
 * This file is generated by jOOQ.
 */
package dev.turbin.jooqtest.jooq.tables.records;


import dev.turbin.jooqtest.jooq.tables.CoreAddress;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * адрес
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CoreAddressRecord extends UpdatableRecordImpl<CoreAddressRecord> implements Record12<Long, Long, Long, Long, Long, Long, OffsetDateTime, OffsetDateTime, String, OffsetDateTime, OffsetDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>passport_international.core_address.core_address_id</code>.
     * идентификатор
     */
    public void setCoreAddressId(Long value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>passport_international.core_address.core_address_id</code>.
     * идентификатор
     */
    public Long getCoreAddressId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>passport_international.core_address.country_id</code>.
     * страна
     */
    public void setCountryId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>passport_international.core_address.country_id</code>.
     * страна
     */
    public Long getCountryId() {
        return (Long) get(1);
    }

    /**
     * Setter for
     * <code>passport_international.core_address.addr_object_id</code>. адресный
     * объект
     */
    public void setAddrObjectId(Long value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>passport_international.core_address.addr_object_id</code>. адресный
     * объект
     */
    public Long getAddrObjectId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>passport_international.core_address.housing_id</code>.
     * жилое помещение
     */
    public void setHousingId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>passport_international.core_address.housing_id</code>.
     * жилое помещение
     */
    public Long getHousingId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>passport_international.core_address.district_id</code>.
     * район города
     */
    public void setDistrictId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>passport_international.core_address.district_id</code>.
     * район города
     */
    public Long getDistrictId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>passport_international.core_address.src_id</code>.
     */
    public void setSrcId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>passport_international.core_address.src_id</code>.
     */
    public Long getSrcId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>passport_international.core_address.create_dttm</code>.
     */
    public void setCreateDttm(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>passport_international.core_address.create_dttm</code>.
     */
    public OffsetDateTime getCreateDttm() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>passport_international.core_address.modify_dttm</code>.
     */
    public void setModifyDttm(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>passport_international.core_address.modify_dttm</code>.
     */
    public OffsetDateTime getModifyDttm() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>passport_international.core_address.action_ind</code>.
     */
    public void setActionInd(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>passport_international.core_address.action_ind</code>.
     */
    public String getActionInd() {
        return (String) get(8);
    }

    /**
     * Setter for <code>passport_international.core_address.eff_dttm</code>.
     */
    public void setEffDttm(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>passport_international.core_address.eff_dttm</code>.
     */
    public OffsetDateTime getEffDttm() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for <code>passport_international.core_address.exp_dttm</code>.
     */
    public void setExpDttm(OffsetDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>passport_international.core_address.exp_dttm</code>.
     */
    public OffsetDateTime getExpDttm() {
        return (OffsetDateTime) get(10);
    }

    /**
     * Setter for
     * <code>passport_international.core_address.old_system_value_cval</code>.
     */
    public void setOldSystemValueCval(String value) {
        set(11, value);
    }

    /**
     * Getter for
     * <code>passport_international.core_address.old_system_value_cval</code>.
     */
    public String getOldSystemValueCval() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, Long, Long, Long, Long, Long, OffsetDateTime, OffsetDateTime, String, OffsetDateTime, OffsetDateTime, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Long, Long, Long, Long, Long, Long, OffsetDateTime, OffsetDateTime, String, OffsetDateTime, OffsetDateTime, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return CoreAddress.CORE_ADDRESS.CORE_ADDRESS_ID;
    }

    @Override
    public Field<Long> field2() {
        return CoreAddress.CORE_ADDRESS.COUNTRY_ID;
    }

    @Override
    public Field<Long> field3() {
        return CoreAddress.CORE_ADDRESS.ADDR_OBJECT_ID;
    }

    @Override
    public Field<Long> field4() {
        return CoreAddress.CORE_ADDRESS.HOUSING_ID;
    }

    @Override
    public Field<Long> field5() {
        return CoreAddress.CORE_ADDRESS.DISTRICT_ID;
    }

    @Override
    public Field<Long> field6() {
        return CoreAddress.CORE_ADDRESS.SRC_ID;
    }

    @Override
    public Field<OffsetDateTime> field7() {
        return CoreAddress.CORE_ADDRESS.CREATE_DTTM;
    }

    @Override
    public Field<OffsetDateTime> field8() {
        return CoreAddress.CORE_ADDRESS.MODIFY_DTTM;
    }

    @Override
    public Field<String> field9() {
        return CoreAddress.CORE_ADDRESS.ACTION_IND;
    }

    @Override
    public Field<OffsetDateTime> field10() {
        return CoreAddress.CORE_ADDRESS.EFF_DTTM;
    }

    @Override
    public Field<OffsetDateTime> field11() {
        return CoreAddress.CORE_ADDRESS.EXP_DTTM;
    }

    @Override
    public Field<String> field12() {
        return CoreAddress.CORE_ADDRESS.OLD_SYSTEM_VALUE_CVAL;
    }

    @Override
    public Long component1() {
        return getCoreAddressId();
    }

    @Override
    public Long component2() {
        return getCountryId();
    }

    @Override
    public Long component3() {
        return getAddrObjectId();
    }

    @Override
    public Long component4() {
        return getHousingId();
    }

    @Override
    public Long component5() {
        return getDistrictId();
    }

    @Override
    public Long component6() {
        return getSrcId();
    }

    @Override
    public OffsetDateTime component7() {
        return getCreateDttm();
    }

    @Override
    public OffsetDateTime component8() {
        return getModifyDttm();
    }

    @Override
    public String component9() {
        return getActionInd();
    }

    @Override
    public OffsetDateTime component10() {
        return getEffDttm();
    }

    @Override
    public OffsetDateTime component11() {
        return getExpDttm();
    }

    @Override
    public String component12() {
        return getOldSystemValueCval();
    }

    @Override
    public Long value1() {
        return getCoreAddressId();
    }

    @Override
    public Long value2() {
        return getCountryId();
    }

    @Override
    public Long value3() {
        return getAddrObjectId();
    }

    @Override
    public Long value4() {
        return getHousingId();
    }

    @Override
    public Long value5() {
        return getDistrictId();
    }

    @Override
    public Long value6() {
        return getSrcId();
    }

    @Override
    public OffsetDateTime value7() {
        return getCreateDttm();
    }

    @Override
    public OffsetDateTime value8() {
        return getModifyDttm();
    }

    @Override
    public String value9() {
        return getActionInd();
    }

    @Override
    public OffsetDateTime value10() {
        return getEffDttm();
    }

    @Override
    public OffsetDateTime value11() {
        return getExpDttm();
    }

    @Override
    public String value12() {
        return getOldSystemValueCval();
    }

    @Override
    public CoreAddressRecord value1(Long value) {
        setCoreAddressId(value);
        return this;
    }

    @Override
    public CoreAddressRecord value2(Long value) {
        setCountryId(value);
        return this;
    }

    @Override
    public CoreAddressRecord value3(Long value) {
        setAddrObjectId(value);
        return this;
    }

    @Override
    public CoreAddressRecord value4(Long value) {
        setHousingId(value);
        return this;
    }

    @Override
    public CoreAddressRecord value5(Long value) {
        setDistrictId(value);
        return this;
    }

    @Override
    public CoreAddressRecord value6(Long value) {
        setSrcId(value);
        return this;
    }

    @Override
    public CoreAddressRecord value7(OffsetDateTime value) {
        setCreateDttm(value);
        return this;
    }

    @Override
    public CoreAddressRecord value8(OffsetDateTime value) {
        setModifyDttm(value);
        return this;
    }

    @Override
    public CoreAddressRecord value9(String value) {
        setActionInd(value);
        return this;
    }

    @Override
    public CoreAddressRecord value10(OffsetDateTime value) {
        setEffDttm(value);
        return this;
    }

    @Override
    public CoreAddressRecord value11(OffsetDateTime value) {
        setExpDttm(value);
        return this;
    }

    @Override
    public CoreAddressRecord value12(String value) {
        setOldSystemValueCval(value);
        return this;
    }

    @Override
    public CoreAddressRecord values(Long value1, Long value2, Long value3, Long value4, Long value5, Long value6, OffsetDateTime value7, OffsetDateTime value8, String value9, OffsetDateTime value10, OffsetDateTime value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CoreAddressRecord
     */
    public CoreAddressRecord() {
        super(CoreAddress.CORE_ADDRESS);
    }

    /**
     * Create a detached, initialised CoreAddressRecord
     */
    public CoreAddressRecord(Long coreAddressId, Long countryId, Long addrObjectId, Long housingId, Long districtId, Long srcId, OffsetDateTime createDttm, OffsetDateTime modifyDttm, String actionInd, OffsetDateTime effDttm, OffsetDateTime expDttm, String oldSystemValueCval) {
        super(CoreAddress.CORE_ADDRESS);

        setCoreAddressId(coreAddressId);
        setCountryId(countryId);
        setAddrObjectId(addrObjectId);
        setHousingId(housingId);
        setDistrictId(districtId);
        setSrcId(srcId);
        setCreateDttm(createDttm);
        setModifyDttm(modifyDttm);
        setActionInd(actionInd);
        setEffDttm(effDttm);
        setExpDttm(expDttm);
        setOldSystemValueCval(oldSystemValueCval);
        resetChangedOnNotNull();
    }
}
