/*
 * This file is generated by jOOQ.
 */
package dev.turbin.jooqtest.jooq.tables.records;


import dev.turbin.jooqtest.jooq.tables.OrganizationInfo;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Таблица информации об организации.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrganizationInfoRecord extends UpdatableRecordImpl<OrganizationInfoRecord> implements Record13<Long, Long, String, String, String, String, Boolean, Long, OffsetDateTime, OffsetDateTime, String, OffsetDateTime, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>passport_international.organization_info.organization_info_id</code>.
     * Идентификатор
     */
    public void setOrganizationInfoId(Long value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>passport_international.organization_info.organization_info_id</code>.
     * Идентификатор
     */
    public Long getOrganizationInfoId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>passport_international.organization_info.organization_id</code>.
     * Организация
     */
    public void setOrganizationId(Long value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>passport_international.organization_info.organization_id</code>.
     * Организация
     */
    public Long getOrganizationId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>passport_international.organization_info.inn</code>. ИНН
     * организации
     */
    public void setInn(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>passport_international.organization_info.inn</code>. ИНН
     * организации
     */
    public String getInn() {
        return (String) get(2);
    }

    /**
     * Setter for <code>passport_international.organization_info.ogrn</code>.
     * ОГРН или идентификатор иностранного юридического лица
     */
    public void setOgrn(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>passport_international.organization_info.ogrn</code>.
     * ОГРН или идентификатор иностранного юридического лица
     */
    public String getOgrn() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>passport_international.organization_info.short_name</code>. Краткое
     * наименование организации
     */
    public void setShortName(String value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>passport_international.organization_info.short_name</code>. Краткое
     * наименование организации
     */
    public String getShortName() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>passport_international.organization_info.full_name</code>. Полное
     * наименование организации
     */
    public void setFullName(String value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>passport_international.organization_info.full_name</code>. Полное
     * наименование организации
     */
    public String getFullName() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>passport_international.organization_info.registered</code>. Флаг
     * постановки на учет юридического лица
     */
    public void setRegistered(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>passport_international.organization_info.registered</code>. Флаг
     * постановки на учет юридического лица
     */
    public Boolean getRegistered() {
        return (Boolean) get(6);
    }

    /**
     * Setter for
     * <code>passport_international.organization_info.category_id</code>.
     * Категория поставщика
     */
    public void setCategoryId(Long value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>passport_international.organization_info.category_id</code>.
     * Категория поставщика
     */
    public Long getCategoryId() {
        return (Long) get(7);
    }

    /**
     * Setter for
     * <code>passport_international.organization_info.create_dttm</code>. Дата
     * время вставки записи в таблицу
     */
    public void setCreateDttm(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>passport_international.organization_info.create_dttm</code>. Дата
     * время вставки записи в таблицу
     */
    public OffsetDateTime getCreateDttm() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for
     * <code>passport_international.organization_info.modify_dttm</code>. Дата
     * время последнего изменения записи
     */
    public void setModifyDttm(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>passport_international.organization_info.modify_dttm</code>. Дата
     * время последнего изменения записи
     */
    public OffsetDateTime getModifyDttm() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for
     * <code>passport_international.organization_info.action_ind</code>.
     * Индикатор операции DML(I-insert,D-delete,U-update)
     */
    public void setActionInd(String value) {
        set(10, value);
    }

    /**
     * Getter for
     * <code>passport_international.organization_info.action_ind</code>.
     * Индикатор операции DML(I-insert,D-delete,U-update)
     */
    public String getActionInd() {
        return (String) get(10);
    }

    /**
     * Setter for
     * <code>passport_international.organization_info.eff_dttm</code>. Поля
     * отображения периода действия технической истории
     */
    public void setEffDttm(OffsetDateTime value) {
        set(11, value);
    }

    /**
     * Getter for
     * <code>passport_international.organization_info.eff_dttm</code>. Поля
     * отображения периода действия технической истории
     */
    public OffsetDateTime getEffDttm() {
        return (OffsetDateTime) get(11);
    }

    /**
     * Setter for
     * <code>passport_international.organization_info.exp_dttm</code>. Поля
     * отображения периода действия технической истории
     */
    public void setExpDttm(OffsetDateTime value) {
        set(12, value);
    }

    /**
     * Getter for
     * <code>passport_international.organization_info.exp_dttm</code>. Поля
     * отображения периода действия технической истории
     */
    public OffsetDateTime getExpDttm() {
        return (OffsetDateTime) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, Long, String, String, String, String, Boolean, Long, OffsetDateTime, OffsetDateTime, String, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Long, Long, String, String, String, String, Boolean, Long, OffsetDateTime, OffsetDateTime, String, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return OrganizationInfo.ORGANIZATION_INFO.ORGANIZATION_INFO_ID;
    }

    @Override
    public Field<Long> field2() {
        return OrganizationInfo.ORGANIZATION_INFO.ORGANIZATION_ID;
    }

    @Override
    public Field<String> field3() {
        return OrganizationInfo.ORGANIZATION_INFO.INN;
    }

    @Override
    public Field<String> field4() {
        return OrganizationInfo.ORGANIZATION_INFO.OGRN;
    }

    @Override
    public Field<String> field5() {
        return OrganizationInfo.ORGANIZATION_INFO.SHORT_NAME;
    }

    @Override
    public Field<String> field6() {
        return OrganizationInfo.ORGANIZATION_INFO.FULL_NAME;
    }

    @Override
    public Field<Boolean> field7() {
        return OrganizationInfo.ORGANIZATION_INFO.REGISTERED;
    }

    @Override
    public Field<Long> field8() {
        return OrganizationInfo.ORGANIZATION_INFO.CATEGORY_ID;
    }

    @Override
    public Field<OffsetDateTime> field9() {
        return OrganizationInfo.ORGANIZATION_INFO.CREATE_DTTM;
    }

    @Override
    public Field<OffsetDateTime> field10() {
        return OrganizationInfo.ORGANIZATION_INFO.MODIFY_DTTM;
    }

    @Override
    public Field<String> field11() {
        return OrganizationInfo.ORGANIZATION_INFO.ACTION_IND;
    }

    @Override
    public Field<OffsetDateTime> field12() {
        return OrganizationInfo.ORGANIZATION_INFO.EFF_DTTM;
    }

    @Override
    public Field<OffsetDateTime> field13() {
        return OrganizationInfo.ORGANIZATION_INFO.EXP_DTTM;
    }

    @Override
    public Long component1() {
        return getOrganizationInfoId();
    }

    @Override
    public Long component2() {
        return getOrganizationId();
    }

    @Override
    public String component3() {
        return getInn();
    }

    @Override
    public String component4() {
        return getOgrn();
    }

    @Override
    public String component5() {
        return getShortName();
    }

    @Override
    public String component6() {
        return getFullName();
    }

    @Override
    public Boolean component7() {
        return getRegistered();
    }

    @Override
    public Long component8() {
        return getCategoryId();
    }

    @Override
    public OffsetDateTime component9() {
        return getCreateDttm();
    }

    @Override
    public OffsetDateTime component10() {
        return getModifyDttm();
    }

    @Override
    public String component11() {
        return getActionInd();
    }

    @Override
    public OffsetDateTime component12() {
        return getEffDttm();
    }

    @Override
    public OffsetDateTime component13() {
        return getExpDttm();
    }

    @Override
    public Long value1() {
        return getOrganizationInfoId();
    }

    @Override
    public Long value2() {
        return getOrganizationId();
    }

    @Override
    public String value3() {
        return getInn();
    }

    @Override
    public String value4() {
        return getOgrn();
    }

    @Override
    public String value5() {
        return getShortName();
    }

    @Override
    public String value6() {
        return getFullName();
    }

    @Override
    public Boolean value7() {
        return getRegistered();
    }

    @Override
    public Long value8() {
        return getCategoryId();
    }

    @Override
    public OffsetDateTime value9() {
        return getCreateDttm();
    }

    @Override
    public OffsetDateTime value10() {
        return getModifyDttm();
    }

    @Override
    public String value11() {
        return getActionInd();
    }

    @Override
    public OffsetDateTime value12() {
        return getEffDttm();
    }

    @Override
    public OffsetDateTime value13() {
        return getExpDttm();
    }

    @Override
    public OrganizationInfoRecord value1(Long value) {
        setOrganizationInfoId(value);
        return this;
    }

    @Override
    public OrganizationInfoRecord value2(Long value) {
        setOrganizationId(value);
        return this;
    }

    @Override
    public OrganizationInfoRecord value3(String value) {
        setInn(value);
        return this;
    }

    @Override
    public OrganizationInfoRecord value4(String value) {
        setOgrn(value);
        return this;
    }

    @Override
    public OrganizationInfoRecord value5(String value) {
        setShortName(value);
        return this;
    }

    @Override
    public OrganizationInfoRecord value6(String value) {
        setFullName(value);
        return this;
    }

    @Override
    public OrganizationInfoRecord value7(Boolean value) {
        setRegistered(value);
        return this;
    }

    @Override
    public OrganizationInfoRecord value8(Long value) {
        setCategoryId(value);
        return this;
    }

    @Override
    public OrganizationInfoRecord value9(OffsetDateTime value) {
        setCreateDttm(value);
        return this;
    }

    @Override
    public OrganizationInfoRecord value10(OffsetDateTime value) {
        setModifyDttm(value);
        return this;
    }

    @Override
    public OrganizationInfoRecord value11(String value) {
        setActionInd(value);
        return this;
    }

    @Override
    public OrganizationInfoRecord value12(OffsetDateTime value) {
        setEffDttm(value);
        return this;
    }

    @Override
    public OrganizationInfoRecord value13(OffsetDateTime value) {
        setExpDttm(value);
        return this;
    }

    @Override
    public OrganizationInfoRecord values(Long value1, Long value2, String value3, String value4, String value5, String value6, Boolean value7, Long value8, OffsetDateTime value9, OffsetDateTime value10, String value11, OffsetDateTime value12, OffsetDateTime value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrganizationInfoRecord
     */
    public OrganizationInfoRecord() {
        super(OrganizationInfo.ORGANIZATION_INFO);
    }

    /**
     * Create a detached, initialised OrganizationInfoRecord
     */
    public OrganizationInfoRecord(Long organizationInfoId, Long organizationId, String inn, String ogrn, String shortName, String fullName, Boolean registered, Long categoryId, OffsetDateTime createDttm, OffsetDateTime modifyDttm, String actionInd, OffsetDateTime effDttm, OffsetDateTime expDttm) {
        super(OrganizationInfo.ORGANIZATION_INFO);

        setOrganizationInfoId(organizationInfoId);
        setOrganizationId(organizationId);
        setInn(inn);
        setOgrn(ogrn);
        setShortName(shortName);
        setFullName(fullName);
        setRegistered(registered);
        setCategoryId(categoryId);
        setCreateDttm(createDttm);
        setModifyDttm(modifyDttm);
        setActionInd(actionInd);
        setEffDttm(effDttm);
        setExpDttm(expDttm);
        resetChangedOnNotNull();
    }
}
