/*
 * This file is generated by jOOQ.
 */
package dev.turbin.jooqtest.jooq.tables.records;


import dev.turbin.jooqtest.jooq.tables.ViewFpaCancelRestrictCase;

import java.time.LocalDate;
import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewFpaCancelRestrictCaseRecord extends TableRecordImpl<ViewFpaCancelRestrictCaseRecord> implements Record16<Long, Long, String, String, LocalDate, LocalDate, LocalDate, String, String, String, Long, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>passport_international.view_fpa_cancel_restrict_case.fpa_cancel_restrict_case_id</code>.
     */
    public void setFpaCancelRestrictCaseId(Long value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_cancel_restrict_case.fpa_cancel_restrict_case_id</code>.
     */
    public Long getFpaCancelRestrictCaseId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_cancel_restrict_case.fpa_case_restrict_id</code>.
     */
    public void setFpaCaseRestrictId(Long value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_cancel_restrict_case.fpa_case_restrict_id</code>.
     */
    public Long getFpaCaseRestrictId() {
        return (Long) get(1);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_cancel_restrict_case.type_doc_cval</code>.
     */
    public void setTypeDocCval(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_cancel_restrict_case.type_doc_cval</code>.
     */
    public String getTypeDocCval() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_cancel_restrict_case.doc_no</code>.
     * Номер документа подтверждающий права в отношении несовершеннолетнего лица
     */
    public void setDocNo(String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_cancel_restrict_case.doc_no</code>.
     * Номер документа подтверждающий права в отношении несовершеннолетнего лица
     */
    public String getDocNo() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_cancel_restrict_case.issue_dt</code>.
     * Дата выдачи документа подтверждающего права в отношении
     * несовершеннолетнего лица
     */
    public void setIssueDt(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_cancel_restrict_case.issue_dt</code>.
     * Дата выдачи документа подтверждающего права в отношении
     * несовершеннолетнего лица
     */
    public LocalDate getIssueDt() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_cancel_restrict_case.end_restrict_from_dt</code>.
     * Дата окончания ограничения с
     */
    public void setEndRestrictFromDt(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_cancel_restrict_case.end_restrict_from_dt</code>.
     * Дата окончания ограничения с
     */
    public LocalDate getEndRestrictFromDt() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_cancel_restrict_case.end_restrict_to_dt</code>.
     * Дата окончания ограничения по
     */
    public void setEndRestrictToDt(LocalDate value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_cancel_restrict_case.end_restrict_to_dt</code>.
     * Дата окончания ограничения по
     */
    public LocalDate getEndRestrictToDt() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_cancel_restrict_case.type_doc_base_cval</code>.
     */
    public void setTypeDocBaseCval(String value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_cancel_restrict_case.type_doc_base_cval</code>.
     */
    public String getTypeDocBaseCval() {
        return (String) get(7);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_cancel_restrict_case.comment_base_desc</code>.
     */
    public void setCommentBaseDesc(String value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_cancel_restrict_case.comment_base_desc</code>.
     */
    public String getCommentBaseDesc() {
        return (String) get(8);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_cancel_restrict_case.comment_desc</code>.
     */
    public void setCommentDesc(String value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_cancel_restrict_case.comment_desc</code>.
     */
    public String getCommentDesc() {
        return (String) get(9);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_cancel_restrict_case.src_id</code>.
     * Идентификатор источника с которого получены информация
     */
    public void setSrcId(Long value) {
        set(10, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_cancel_restrict_case.src_id</code>.
     * Идентификатор источника с которого получены информация
     */
    public Long getSrcId() {
        return (Long) get(10);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_cancel_restrict_case.create_dttm</code>.
     * Дата время вставки записи в таблицу
     */
    public void setCreateDttm(OffsetDateTime value) {
        set(11, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_cancel_restrict_case.create_dttm</code>.
     * Дата время вставки записи в таблицу
     */
    public OffsetDateTime getCreateDttm() {
        return (OffsetDateTime) get(11);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_cancel_restrict_case.modify_dttm</code>.
     * Дата время последнего изменения записи
     */
    public void setModifyDttm(OffsetDateTime value) {
        set(12, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_cancel_restrict_case.modify_dttm</code>.
     * Дата время последнего изменения записи
     */
    public OffsetDateTime getModifyDttm() {
        return (OffsetDateTime) get(12);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_cancel_restrict_case.exp_dttm</code>.
     * Поля отображения периода действия технической истории
     */
    public void setExpDttm(OffsetDateTime value) {
        set(13, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_cancel_restrict_case.exp_dttm</code>.
     * Поля отображения периода действия технической истории
     */
    public OffsetDateTime getExpDttm() {
        return (OffsetDateTime) get(13);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_cancel_restrict_case.eff_dttm</code>.
     * Поля отображения периода действия технической истории
     */
    public void setEffDttm(OffsetDateTime value) {
        set(14, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_cancel_restrict_case.eff_dttm</code>.
     * Поля отображения периода действия технической истории
     */
    public OffsetDateTime getEffDttm() {
        return (OffsetDateTime) get(14);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_cancel_restrict_case.action_ind</code>.
     * Индикатор операции DML(I-insert,D-delete,U-update)
     */
    public void setActionInd(String value) {
        set(15, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_cancel_restrict_case.action_ind</code>.
     * Индикатор операции DML(I-insert,D-delete,U-update)
     */
    public String getActionInd() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row16<Long, Long, String, String, LocalDate, LocalDate, LocalDate, String, String, String, Long, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, String> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    public Row16<Long, Long, String, String, LocalDate, LocalDate, LocalDate, String, String, String, Long, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, String> valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ViewFpaCancelRestrictCase.VIEW_FPA_CANCEL_RESTRICT_CASE.FPA_CANCEL_RESTRICT_CASE_ID;
    }

    @Override
    public Field<Long> field2() {
        return ViewFpaCancelRestrictCase.VIEW_FPA_CANCEL_RESTRICT_CASE.FPA_CASE_RESTRICT_ID;
    }

    @Override
    public Field<String> field3() {
        return ViewFpaCancelRestrictCase.VIEW_FPA_CANCEL_RESTRICT_CASE.TYPE_DOC_CVAL;
    }

    @Override
    public Field<String> field4() {
        return ViewFpaCancelRestrictCase.VIEW_FPA_CANCEL_RESTRICT_CASE.DOC_NO;
    }

    @Override
    public Field<LocalDate> field5() {
        return ViewFpaCancelRestrictCase.VIEW_FPA_CANCEL_RESTRICT_CASE.ISSUE_DT;
    }

    @Override
    public Field<LocalDate> field6() {
        return ViewFpaCancelRestrictCase.VIEW_FPA_CANCEL_RESTRICT_CASE.END_RESTRICT_FROM_DT;
    }

    @Override
    public Field<LocalDate> field7() {
        return ViewFpaCancelRestrictCase.VIEW_FPA_CANCEL_RESTRICT_CASE.END_RESTRICT_TO_DT;
    }

    @Override
    public Field<String> field8() {
        return ViewFpaCancelRestrictCase.VIEW_FPA_CANCEL_RESTRICT_CASE.TYPE_DOC_BASE_CVAL;
    }

    @Override
    public Field<String> field9() {
        return ViewFpaCancelRestrictCase.VIEW_FPA_CANCEL_RESTRICT_CASE.COMMENT_BASE_DESC;
    }

    @Override
    public Field<String> field10() {
        return ViewFpaCancelRestrictCase.VIEW_FPA_CANCEL_RESTRICT_CASE.COMMENT_DESC;
    }

    @Override
    public Field<Long> field11() {
        return ViewFpaCancelRestrictCase.VIEW_FPA_CANCEL_RESTRICT_CASE.SRC_ID;
    }

    @Override
    public Field<OffsetDateTime> field12() {
        return ViewFpaCancelRestrictCase.VIEW_FPA_CANCEL_RESTRICT_CASE.CREATE_DTTM;
    }

    @Override
    public Field<OffsetDateTime> field13() {
        return ViewFpaCancelRestrictCase.VIEW_FPA_CANCEL_RESTRICT_CASE.MODIFY_DTTM;
    }

    @Override
    public Field<OffsetDateTime> field14() {
        return ViewFpaCancelRestrictCase.VIEW_FPA_CANCEL_RESTRICT_CASE.EXP_DTTM;
    }

    @Override
    public Field<OffsetDateTime> field15() {
        return ViewFpaCancelRestrictCase.VIEW_FPA_CANCEL_RESTRICT_CASE.EFF_DTTM;
    }

    @Override
    public Field<String> field16() {
        return ViewFpaCancelRestrictCase.VIEW_FPA_CANCEL_RESTRICT_CASE.ACTION_IND;
    }

    @Override
    public Long component1() {
        return getFpaCancelRestrictCaseId();
    }

    @Override
    public Long component2() {
        return getFpaCaseRestrictId();
    }

    @Override
    public String component3() {
        return getTypeDocCval();
    }

    @Override
    public String component4() {
        return getDocNo();
    }

    @Override
    public LocalDate component5() {
        return getIssueDt();
    }

    @Override
    public LocalDate component6() {
        return getEndRestrictFromDt();
    }

    @Override
    public LocalDate component7() {
        return getEndRestrictToDt();
    }

    @Override
    public String component8() {
        return getTypeDocBaseCval();
    }

    @Override
    public String component9() {
        return getCommentBaseDesc();
    }

    @Override
    public String component10() {
        return getCommentDesc();
    }

    @Override
    public Long component11() {
        return getSrcId();
    }

    @Override
    public OffsetDateTime component12() {
        return getCreateDttm();
    }

    @Override
    public OffsetDateTime component13() {
        return getModifyDttm();
    }

    @Override
    public OffsetDateTime component14() {
        return getExpDttm();
    }

    @Override
    public OffsetDateTime component15() {
        return getEffDttm();
    }

    @Override
    public String component16() {
        return getActionInd();
    }

    @Override
    public Long value1() {
        return getFpaCancelRestrictCaseId();
    }

    @Override
    public Long value2() {
        return getFpaCaseRestrictId();
    }

    @Override
    public String value3() {
        return getTypeDocCval();
    }

    @Override
    public String value4() {
        return getDocNo();
    }

    @Override
    public LocalDate value5() {
        return getIssueDt();
    }

    @Override
    public LocalDate value6() {
        return getEndRestrictFromDt();
    }

    @Override
    public LocalDate value7() {
        return getEndRestrictToDt();
    }

    @Override
    public String value8() {
        return getTypeDocBaseCval();
    }

    @Override
    public String value9() {
        return getCommentBaseDesc();
    }

    @Override
    public String value10() {
        return getCommentDesc();
    }

    @Override
    public Long value11() {
        return getSrcId();
    }

    @Override
    public OffsetDateTime value12() {
        return getCreateDttm();
    }

    @Override
    public OffsetDateTime value13() {
        return getModifyDttm();
    }

    @Override
    public OffsetDateTime value14() {
        return getExpDttm();
    }

    @Override
    public OffsetDateTime value15() {
        return getEffDttm();
    }

    @Override
    public String value16() {
        return getActionInd();
    }

    @Override
    public ViewFpaCancelRestrictCaseRecord value1(Long value) {
        setFpaCancelRestrictCaseId(value);
        return this;
    }

    @Override
    public ViewFpaCancelRestrictCaseRecord value2(Long value) {
        setFpaCaseRestrictId(value);
        return this;
    }

    @Override
    public ViewFpaCancelRestrictCaseRecord value3(String value) {
        setTypeDocCval(value);
        return this;
    }

    @Override
    public ViewFpaCancelRestrictCaseRecord value4(String value) {
        setDocNo(value);
        return this;
    }

    @Override
    public ViewFpaCancelRestrictCaseRecord value5(LocalDate value) {
        setIssueDt(value);
        return this;
    }

    @Override
    public ViewFpaCancelRestrictCaseRecord value6(LocalDate value) {
        setEndRestrictFromDt(value);
        return this;
    }

    @Override
    public ViewFpaCancelRestrictCaseRecord value7(LocalDate value) {
        setEndRestrictToDt(value);
        return this;
    }

    @Override
    public ViewFpaCancelRestrictCaseRecord value8(String value) {
        setTypeDocBaseCval(value);
        return this;
    }

    @Override
    public ViewFpaCancelRestrictCaseRecord value9(String value) {
        setCommentBaseDesc(value);
        return this;
    }

    @Override
    public ViewFpaCancelRestrictCaseRecord value10(String value) {
        setCommentDesc(value);
        return this;
    }

    @Override
    public ViewFpaCancelRestrictCaseRecord value11(Long value) {
        setSrcId(value);
        return this;
    }

    @Override
    public ViewFpaCancelRestrictCaseRecord value12(OffsetDateTime value) {
        setCreateDttm(value);
        return this;
    }

    @Override
    public ViewFpaCancelRestrictCaseRecord value13(OffsetDateTime value) {
        setModifyDttm(value);
        return this;
    }

    @Override
    public ViewFpaCancelRestrictCaseRecord value14(OffsetDateTime value) {
        setExpDttm(value);
        return this;
    }

    @Override
    public ViewFpaCancelRestrictCaseRecord value15(OffsetDateTime value) {
        setEffDttm(value);
        return this;
    }

    @Override
    public ViewFpaCancelRestrictCaseRecord value16(String value) {
        setActionInd(value);
        return this;
    }

    @Override
    public ViewFpaCancelRestrictCaseRecord values(Long value1, Long value2, String value3, String value4, LocalDate value5, LocalDate value6, LocalDate value7, String value8, String value9, String value10, Long value11, OffsetDateTime value12, OffsetDateTime value13, OffsetDateTime value14, OffsetDateTime value15, String value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewFpaCancelRestrictCaseRecord
     */
    public ViewFpaCancelRestrictCaseRecord() {
        super(ViewFpaCancelRestrictCase.VIEW_FPA_CANCEL_RESTRICT_CASE);
    }

    /**
     * Create a detached, initialised ViewFpaCancelRestrictCaseRecord
     */
    public ViewFpaCancelRestrictCaseRecord(Long fpaCancelRestrictCaseId, Long fpaCaseRestrictId, String typeDocCval, String docNo, LocalDate issueDt, LocalDate endRestrictFromDt, LocalDate endRestrictToDt, String typeDocBaseCval, String commentBaseDesc, String commentDesc, Long srcId, OffsetDateTime createDttm, OffsetDateTime modifyDttm, OffsetDateTime expDttm, OffsetDateTime effDttm, String actionInd) {
        super(ViewFpaCancelRestrictCase.VIEW_FPA_CANCEL_RESTRICT_CASE);

        setFpaCancelRestrictCaseId(fpaCancelRestrictCaseId);
        setFpaCaseRestrictId(fpaCaseRestrictId);
        setTypeDocCval(typeDocCval);
        setDocNo(docNo);
        setIssueDt(issueDt);
        setEndRestrictFromDt(endRestrictFromDt);
        setEndRestrictToDt(endRestrictToDt);
        setTypeDocBaseCval(typeDocBaseCval);
        setCommentBaseDesc(commentBaseDesc);
        setCommentDesc(commentDesc);
        setSrcId(srcId);
        setCreateDttm(createDttm);
        setModifyDttm(modifyDttm);
        setExpDttm(expDttm);
        setEffDttm(effDttm);
        setActionInd(actionInd);
        resetChangedOnNotNull();
    }
}
