/*
 * This file is generated by jOOQ.
 */
package dev.turbin.jooqtest.jooq.tables.records;


import dev.turbin.jooqtest.jooq.tables.ViewFpaBaseRestrict;

import java.time.LocalDate;
import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewFpaBaseRestrictRecord extends TableRecordImpl<ViewFpaBaseRestrictRecord> implements Record12<Long, Long, Long, Long, String, LocalDate, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>passport_international.view_fpa_base_restrict.fpa_base_restrict_id</code>.
     */
    public void setFpaBaseRestrictId(Long value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_base_restrict.fpa_base_restrict_id</code>.
     */
    public Long getFpaBaseRestrictId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_base_restrict.category_id</code>.
     */
    public void setCategoryId(Long value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_base_restrict.category_id</code>.
     */
    public Long getCategoryId() {
        return (Long) get(1);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_base_restrict.status_basis_id</code>.
     */
    public void setStatusBasisId(Long value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_base_restrict.status_basis_id</code>.
     */
    public Long getStatusBasisId() {
        return (Long) get(2);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_base_restrict.court_name_id</code>.
     */
    public void setCourtNameId(Long value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_base_restrict.court_name_id</code>.
     */
    public Long getCourtNameId() {
        return (Long) get(3);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_base_restrict.court_decision_no</code>.
     */
    public void setCourtDecisionNo(String value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_base_restrict.court_decision_no</code>.
     */
    public String getCourtDecisionNo() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_base_restrict.court_decision_dt</code>.
     */
    public void setCourtDecisionDt(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_base_restrict.court_decision_dt</code>.
     */
    public LocalDate getCourtDecisionDt() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_base_restrict.comment_desc</code>.
     */
    public void setCommentDesc(String value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_base_restrict.comment_desc</code>.
     */
    public String getCommentDesc() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_base_restrict.action_ind</code>.
     */
    public void setActionInd(String value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_base_restrict.action_ind</code>.
     */
    public String getActionInd() {
        return (String) get(7);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_base_restrict.create_dttm</code>.
     */
    public void setCreateDttm(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_base_restrict.create_dttm</code>.
     */
    public OffsetDateTime getCreateDttm() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_base_restrict.modify_dttm</code>.
     */
    public void setModifyDttm(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_base_restrict.modify_dttm</code>.
     */
    public OffsetDateTime getModifyDttm() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_base_restrict.eff_dttm</code>.
     */
    public void setEffDttm(OffsetDateTime value) {
        set(10, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_base_restrict.eff_dttm</code>.
     */
    public OffsetDateTime getEffDttm() {
        return (OffsetDateTime) get(10);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_base_restrict.exp_dttm</code>.
     */
    public void setExpDttm(OffsetDateTime value) {
        set(11, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_base_restrict.exp_dttm</code>.
     */
    public OffsetDateTime getExpDttm() {
        return (OffsetDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, Long, Long, Long, String, LocalDate, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Long, Long, Long, Long, String, LocalDate, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ViewFpaBaseRestrict.VIEW_FPA_BASE_RESTRICT.FPA_BASE_RESTRICT_ID;
    }

    @Override
    public Field<Long> field2() {
        return ViewFpaBaseRestrict.VIEW_FPA_BASE_RESTRICT.CATEGORY_ID;
    }

    @Override
    public Field<Long> field3() {
        return ViewFpaBaseRestrict.VIEW_FPA_BASE_RESTRICT.STATUS_BASIS_ID;
    }

    @Override
    public Field<Long> field4() {
        return ViewFpaBaseRestrict.VIEW_FPA_BASE_RESTRICT.COURT_NAME_ID;
    }

    @Override
    public Field<String> field5() {
        return ViewFpaBaseRestrict.VIEW_FPA_BASE_RESTRICT.COURT_DECISION_NO;
    }

    @Override
    public Field<LocalDate> field6() {
        return ViewFpaBaseRestrict.VIEW_FPA_BASE_RESTRICT.COURT_DECISION_DT;
    }

    @Override
    public Field<String> field7() {
        return ViewFpaBaseRestrict.VIEW_FPA_BASE_RESTRICT.COMMENT_DESC;
    }

    @Override
    public Field<String> field8() {
        return ViewFpaBaseRestrict.VIEW_FPA_BASE_RESTRICT.ACTION_IND;
    }

    @Override
    public Field<OffsetDateTime> field9() {
        return ViewFpaBaseRestrict.VIEW_FPA_BASE_RESTRICT.CREATE_DTTM;
    }

    @Override
    public Field<OffsetDateTime> field10() {
        return ViewFpaBaseRestrict.VIEW_FPA_BASE_RESTRICT.MODIFY_DTTM;
    }

    @Override
    public Field<OffsetDateTime> field11() {
        return ViewFpaBaseRestrict.VIEW_FPA_BASE_RESTRICT.EFF_DTTM;
    }

    @Override
    public Field<OffsetDateTime> field12() {
        return ViewFpaBaseRestrict.VIEW_FPA_BASE_RESTRICT.EXP_DTTM;
    }

    @Override
    public Long component1() {
        return getFpaBaseRestrictId();
    }

    @Override
    public Long component2() {
        return getCategoryId();
    }

    @Override
    public Long component3() {
        return getStatusBasisId();
    }

    @Override
    public Long component4() {
        return getCourtNameId();
    }

    @Override
    public String component5() {
        return getCourtDecisionNo();
    }

    @Override
    public LocalDate component6() {
        return getCourtDecisionDt();
    }

    @Override
    public String component7() {
        return getCommentDesc();
    }

    @Override
    public String component8() {
        return getActionInd();
    }

    @Override
    public OffsetDateTime component9() {
        return getCreateDttm();
    }

    @Override
    public OffsetDateTime component10() {
        return getModifyDttm();
    }

    @Override
    public OffsetDateTime component11() {
        return getEffDttm();
    }

    @Override
    public OffsetDateTime component12() {
        return getExpDttm();
    }

    @Override
    public Long value1() {
        return getFpaBaseRestrictId();
    }

    @Override
    public Long value2() {
        return getCategoryId();
    }

    @Override
    public Long value3() {
        return getStatusBasisId();
    }

    @Override
    public Long value4() {
        return getCourtNameId();
    }

    @Override
    public String value5() {
        return getCourtDecisionNo();
    }

    @Override
    public LocalDate value6() {
        return getCourtDecisionDt();
    }

    @Override
    public String value7() {
        return getCommentDesc();
    }

    @Override
    public String value8() {
        return getActionInd();
    }

    @Override
    public OffsetDateTime value9() {
        return getCreateDttm();
    }

    @Override
    public OffsetDateTime value10() {
        return getModifyDttm();
    }

    @Override
    public OffsetDateTime value11() {
        return getEffDttm();
    }

    @Override
    public OffsetDateTime value12() {
        return getExpDttm();
    }

    @Override
    public ViewFpaBaseRestrictRecord value1(Long value) {
        setFpaBaseRestrictId(value);
        return this;
    }

    @Override
    public ViewFpaBaseRestrictRecord value2(Long value) {
        setCategoryId(value);
        return this;
    }

    @Override
    public ViewFpaBaseRestrictRecord value3(Long value) {
        setStatusBasisId(value);
        return this;
    }

    @Override
    public ViewFpaBaseRestrictRecord value4(Long value) {
        setCourtNameId(value);
        return this;
    }

    @Override
    public ViewFpaBaseRestrictRecord value5(String value) {
        setCourtDecisionNo(value);
        return this;
    }

    @Override
    public ViewFpaBaseRestrictRecord value6(LocalDate value) {
        setCourtDecisionDt(value);
        return this;
    }

    @Override
    public ViewFpaBaseRestrictRecord value7(String value) {
        setCommentDesc(value);
        return this;
    }

    @Override
    public ViewFpaBaseRestrictRecord value8(String value) {
        setActionInd(value);
        return this;
    }

    @Override
    public ViewFpaBaseRestrictRecord value9(OffsetDateTime value) {
        setCreateDttm(value);
        return this;
    }

    @Override
    public ViewFpaBaseRestrictRecord value10(OffsetDateTime value) {
        setModifyDttm(value);
        return this;
    }

    @Override
    public ViewFpaBaseRestrictRecord value11(OffsetDateTime value) {
        setEffDttm(value);
        return this;
    }

    @Override
    public ViewFpaBaseRestrictRecord value12(OffsetDateTime value) {
        setExpDttm(value);
        return this;
    }

    @Override
    public ViewFpaBaseRestrictRecord values(Long value1, Long value2, Long value3, Long value4, String value5, LocalDate value6, String value7, String value8, OffsetDateTime value9, OffsetDateTime value10, OffsetDateTime value11, OffsetDateTime value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewFpaBaseRestrictRecord
     */
    public ViewFpaBaseRestrictRecord() {
        super(ViewFpaBaseRestrict.VIEW_FPA_BASE_RESTRICT);
    }

    /**
     * Create a detached, initialised ViewFpaBaseRestrictRecord
     */
    public ViewFpaBaseRestrictRecord(Long fpaBaseRestrictId, Long categoryId, Long statusBasisId, Long courtNameId, String courtDecisionNo, LocalDate courtDecisionDt, String commentDesc, String actionInd, OffsetDateTime createDttm, OffsetDateTime modifyDttm, OffsetDateTime effDttm, OffsetDateTime expDttm) {
        super(ViewFpaBaseRestrict.VIEW_FPA_BASE_RESTRICT);

        setFpaBaseRestrictId(fpaBaseRestrictId);
        setCategoryId(categoryId);
        setStatusBasisId(statusBasisId);
        setCourtNameId(courtNameId);
        setCourtDecisionNo(courtDecisionNo);
        setCourtDecisionDt(courtDecisionDt);
        setCommentDesc(commentDesc);
        setActionInd(actionInd);
        setCreateDttm(createDttm);
        setModifyDttm(modifyDttm);
        setEffDttm(effDttm);
        setExpDttm(expDttm);
        resetChangedOnNotNull();
    }
}
