/*
 * This file is generated by jOOQ.
 */
package dev.turbin.jooqtest.jooq.tables.records;


import dev.turbin.jooqtest.jooq.tables.ViewFpaTranslateName;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewFpaTranslateNameRecord extends TableRecordImpl<ViewFpaTranslateNameRecord> implements Record11<Long, String, String, String, String, Long, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>passport_international.view_fpa_translate_name.fpa_translate_name_id</code>.
     */
    public void setFpaTranslateNameId(Long value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_translate_name.fpa_translate_name_id</code>.
     */
    public Long getFpaTranslateNameId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_translate_name.first_name</code>.
     * Обновленное имя
     */
    public void setFirstName(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_translate_name.first_name</code>.
     * Обновленное имя
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_translate_name.middle_name</code>.
     * Обновленное отчество
     */
    public void setMiddleName(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_translate_name.middle_name</code>.
     * Обновленное отчество
     */
    public String getMiddleName() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_translate_name.last_name</code>.
     * Обновленая фамилия
     */
    public void setLastName(String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_translate_name.last_name</code>.
     * Обновленая фамилия
     */
    public String getLastName() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_translate_name.reason_translate_desc</code>.
     */
    public void setReasonTranslateDesc(String value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_translate_name.reason_translate_desc</code>.
     */
    public String getReasonTranslateDesc() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_translate_name.src_id</code>.
     */
    public void setSrcId(Long value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_translate_name.src_id</code>.
     */
    public Long getSrcId() {
        return (Long) get(5);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_translate_name.create_dttm</code>.
     */
    public void setCreateDttm(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_translate_name.create_dttm</code>.
     */
    public OffsetDateTime getCreateDttm() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_translate_name.modify_dttm</code>.
     */
    public void setModifyDttm(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_translate_name.modify_dttm</code>.
     */
    public OffsetDateTime getModifyDttm() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_translate_name.exp_dttm</code>.
     */
    public void setExpDttm(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_translate_name.exp_dttm</code>.
     */
    public OffsetDateTime getExpDttm() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_translate_name.eff_dttm</code>.
     */
    public void setEffDttm(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_translate_name.eff_dttm</code>.
     */
    public OffsetDateTime getEffDttm() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for
     * <code>passport_international.view_fpa_translate_name.action_ind</code>.
     */
    public void setActionInd(String value) {
        set(10, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_fpa_translate_name.action_ind</code>.
     */
    public String getActionInd() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, String, String, String, String, Long, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Long, String, String, String, String, Long, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ViewFpaTranslateName.VIEW_FPA_TRANSLATE_NAME.FPA_TRANSLATE_NAME_ID;
    }

    @Override
    public Field<String> field2() {
        return ViewFpaTranslateName.VIEW_FPA_TRANSLATE_NAME.FIRST_NAME;
    }

    @Override
    public Field<String> field3() {
        return ViewFpaTranslateName.VIEW_FPA_TRANSLATE_NAME.MIDDLE_NAME;
    }

    @Override
    public Field<String> field4() {
        return ViewFpaTranslateName.VIEW_FPA_TRANSLATE_NAME.LAST_NAME;
    }

    @Override
    public Field<String> field5() {
        return ViewFpaTranslateName.VIEW_FPA_TRANSLATE_NAME.REASON_TRANSLATE_DESC;
    }

    @Override
    public Field<Long> field6() {
        return ViewFpaTranslateName.VIEW_FPA_TRANSLATE_NAME.SRC_ID;
    }

    @Override
    public Field<OffsetDateTime> field7() {
        return ViewFpaTranslateName.VIEW_FPA_TRANSLATE_NAME.CREATE_DTTM;
    }

    @Override
    public Field<OffsetDateTime> field8() {
        return ViewFpaTranslateName.VIEW_FPA_TRANSLATE_NAME.MODIFY_DTTM;
    }

    @Override
    public Field<OffsetDateTime> field9() {
        return ViewFpaTranslateName.VIEW_FPA_TRANSLATE_NAME.EXP_DTTM;
    }

    @Override
    public Field<OffsetDateTime> field10() {
        return ViewFpaTranslateName.VIEW_FPA_TRANSLATE_NAME.EFF_DTTM;
    }

    @Override
    public Field<String> field11() {
        return ViewFpaTranslateName.VIEW_FPA_TRANSLATE_NAME.ACTION_IND;
    }

    @Override
    public Long component1() {
        return getFpaTranslateNameId();
    }

    @Override
    public String component2() {
        return getFirstName();
    }

    @Override
    public String component3() {
        return getMiddleName();
    }

    @Override
    public String component4() {
        return getLastName();
    }

    @Override
    public String component5() {
        return getReasonTranslateDesc();
    }

    @Override
    public Long component6() {
        return getSrcId();
    }

    @Override
    public OffsetDateTime component7() {
        return getCreateDttm();
    }

    @Override
    public OffsetDateTime component8() {
        return getModifyDttm();
    }

    @Override
    public OffsetDateTime component9() {
        return getExpDttm();
    }

    @Override
    public OffsetDateTime component10() {
        return getEffDttm();
    }

    @Override
    public String component11() {
        return getActionInd();
    }

    @Override
    public Long value1() {
        return getFpaTranslateNameId();
    }

    @Override
    public String value2() {
        return getFirstName();
    }

    @Override
    public String value3() {
        return getMiddleName();
    }

    @Override
    public String value4() {
        return getLastName();
    }

    @Override
    public String value5() {
        return getReasonTranslateDesc();
    }

    @Override
    public Long value6() {
        return getSrcId();
    }

    @Override
    public OffsetDateTime value7() {
        return getCreateDttm();
    }

    @Override
    public OffsetDateTime value8() {
        return getModifyDttm();
    }

    @Override
    public OffsetDateTime value9() {
        return getExpDttm();
    }

    @Override
    public OffsetDateTime value10() {
        return getEffDttm();
    }

    @Override
    public String value11() {
        return getActionInd();
    }

    @Override
    public ViewFpaTranslateNameRecord value1(Long value) {
        setFpaTranslateNameId(value);
        return this;
    }

    @Override
    public ViewFpaTranslateNameRecord value2(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public ViewFpaTranslateNameRecord value3(String value) {
        setMiddleName(value);
        return this;
    }

    @Override
    public ViewFpaTranslateNameRecord value4(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public ViewFpaTranslateNameRecord value5(String value) {
        setReasonTranslateDesc(value);
        return this;
    }

    @Override
    public ViewFpaTranslateNameRecord value6(Long value) {
        setSrcId(value);
        return this;
    }

    @Override
    public ViewFpaTranslateNameRecord value7(OffsetDateTime value) {
        setCreateDttm(value);
        return this;
    }

    @Override
    public ViewFpaTranslateNameRecord value8(OffsetDateTime value) {
        setModifyDttm(value);
        return this;
    }

    @Override
    public ViewFpaTranslateNameRecord value9(OffsetDateTime value) {
        setExpDttm(value);
        return this;
    }

    @Override
    public ViewFpaTranslateNameRecord value10(OffsetDateTime value) {
        setEffDttm(value);
        return this;
    }

    @Override
    public ViewFpaTranslateNameRecord value11(String value) {
        setActionInd(value);
        return this;
    }

    @Override
    public ViewFpaTranslateNameRecord values(Long value1, String value2, String value3, String value4, String value5, Long value6, OffsetDateTime value7, OffsetDateTime value8, OffsetDateTime value9, OffsetDateTime value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewFpaTranslateNameRecord
     */
    public ViewFpaTranslateNameRecord() {
        super(ViewFpaTranslateName.VIEW_FPA_TRANSLATE_NAME);
    }

    /**
     * Create a detached, initialised ViewFpaTranslateNameRecord
     */
    public ViewFpaTranslateNameRecord(Long fpaTranslateNameId, String firstName, String middleName, String lastName, String reasonTranslateDesc, Long srcId, OffsetDateTime createDttm, OffsetDateTime modifyDttm, OffsetDateTime expDttm, OffsetDateTime effDttm, String actionInd) {
        super(ViewFpaTranslateName.VIEW_FPA_TRANSLATE_NAME);

        setFpaTranslateNameId(fpaTranslateNameId);
        setFirstName(firstName);
        setMiddleName(middleName);
        setLastName(lastName);
        setReasonTranslateDesc(reasonTranslateDesc);
        setSrcId(srcId);
        setCreateDttm(createDttm);
        setModifyDttm(modifyDttm);
        setExpDttm(expDttm);
        setEffDttm(effDttm);
        setActionInd(actionInd);
        resetChangedOnNotNull();
    }
}
