/*
 * This file is generated by jOOQ.
 */
package dev.turbin.jooqtest.jooq.tables.records;


import dev.turbin.jooqtest.jooq.tables.ViewCoreProcedure;

import java.time.LocalDate;
import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewCoreProcedureRecord extends TableRecordImpl<ViewCoreProcedureRecord> implements Record10<Long, Long, OffsetDateTime, Long, LocalDate, Long, String, OffsetDateTime, OffsetDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>passport_international.view_core_procedure.core_procedure_id</code>.
     */
    public void setCoreProcedureId(Long value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_core_procedure.core_procedure_id</code>.
     */
    public Long getCoreProcedureId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>passport_international.view_core_procedure.operation_id</code>.
     */
    public void setOperationId(Long value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_core_procedure.operation_id</code>.
     */
    public Long getOperationId() {
        return (Long) get(1);
    }

    /**
     * Setter for
     * <code>passport_international.view_core_procedure.operation_dttm</code>.
     */
    public void setOperationDttm(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_core_procedure.operation_dttm</code>.
     */
    public OffsetDateTime getOperationDttm() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for
     * <code>passport_international.view_core_procedure.status_id</code>.
     */
    public void setStatusId(Long value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_core_procedure.status_id</code>.
     */
    public Long getStatusId() {
        return (Long) get(3);
    }

    /**
     * Setter for
     * <code>passport_international.view_core_procedure.status_dt</code>.
     */
    public void setStatusDt(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_core_procedure.status_dt</code>.
     */
    public LocalDate getStatusDt() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for
     * <code>passport_international.view_core_procedure.core_case_id</code>.
     */
    public void setCoreCaseId(Long value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_core_procedure.core_case_id</code>.
     */
    public Long getCoreCaseId() {
        return (Long) get(5);
    }

    /**
     * Setter for
     * <code>passport_international.view_core_procedure.create_user</code>.
     */
    public void setCreateUser(String value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_core_procedure.create_user</code>.
     */
    public String getCreateUser() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>passport_international.view_core_procedure.create_dttm</code>.
     */
    public void setCreateDttm(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_core_procedure.create_dttm</code>.
     */
    public OffsetDateTime getCreateDttm() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for
     * <code>passport_international.view_core_procedure.modify_dttm</code>.
     */
    public void setModifyDttm(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_core_procedure.modify_dttm</code>.
     */
    public OffsetDateTime getModifyDttm() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for
     * <code>passport_international.view_core_procedure.action_ind</code>.
     */
    public void setActionInd(String value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>passport_international.view_core_procedure.action_ind</code>.
     */
    public String getActionInd() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, Long, OffsetDateTime, Long, LocalDate, Long, String, OffsetDateTime, OffsetDateTime, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, Long, OffsetDateTime, Long, LocalDate, Long, String, OffsetDateTime, OffsetDateTime, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ViewCoreProcedure.VIEW_CORE_PROCEDURE.CORE_PROCEDURE_ID;
    }

    @Override
    public Field<Long> field2() {
        return ViewCoreProcedure.VIEW_CORE_PROCEDURE.OPERATION_ID;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return ViewCoreProcedure.VIEW_CORE_PROCEDURE.OPERATION_DTTM;
    }

    @Override
    public Field<Long> field4() {
        return ViewCoreProcedure.VIEW_CORE_PROCEDURE.STATUS_ID;
    }

    @Override
    public Field<LocalDate> field5() {
        return ViewCoreProcedure.VIEW_CORE_PROCEDURE.STATUS_DT;
    }

    @Override
    public Field<Long> field6() {
        return ViewCoreProcedure.VIEW_CORE_PROCEDURE.CORE_CASE_ID;
    }

    @Override
    public Field<String> field7() {
        return ViewCoreProcedure.VIEW_CORE_PROCEDURE.CREATE_USER;
    }

    @Override
    public Field<OffsetDateTime> field8() {
        return ViewCoreProcedure.VIEW_CORE_PROCEDURE.CREATE_DTTM;
    }

    @Override
    public Field<OffsetDateTime> field9() {
        return ViewCoreProcedure.VIEW_CORE_PROCEDURE.MODIFY_DTTM;
    }

    @Override
    public Field<String> field10() {
        return ViewCoreProcedure.VIEW_CORE_PROCEDURE.ACTION_IND;
    }

    @Override
    public Long component1() {
        return getCoreProcedureId();
    }

    @Override
    public Long component2() {
        return getOperationId();
    }

    @Override
    public OffsetDateTime component3() {
        return getOperationDttm();
    }

    @Override
    public Long component4() {
        return getStatusId();
    }

    @Override
    public LocalDate component5() {
        return getStatusDt();
    }

    @Override
    public Long component6() {
        return getCoreCaseId();
    }

    @Override
    public String component7() {
        return getCreateUser();
    }

    @Override
    public OffsetDateTime component8() {
        return getCreateDttm();
    }

    @Override
    public OffsetDateTime component9() {
        return getModifyDttm();
    }

    @Override
    public String component10() {
        return getActionInd();
    }

    @Override
    public Long value1() {
        return getCoreProcedureId();
    }

    @Override
    public Long value2() {
        return getOperationId();
    }

    @Override
    public OffsetDateTime value3() {
        return getOperationDttm();
    }

    @Override
    public Long value4() {
        return getStatusId();
    }

    @Override
    public LocalDate value5() {
        return getStatusDt();
    }

    @Override
    public Long value6() {
        return getCoreCaseId();
    }

    @Override
    public String value7() {
        return getCreateUser();
    }

    @Override
    public OffsetDateTime value8() {
        return getCreateDttm();
    }

    @Override
    public OffsetDateTime value9() {
        return getModifyDttm();
    }

    @Override
    public String value10() {
        return getActionInd();
    }

    @Override
    public ViewCoreProcedureRecord value1(Long value) {
        setCoreProcedureId(value);
        return this;
    }

    @Override
    public ViewCoreProcedureRecord value2(Long value) {
        setOperationId(value);
        return this;
    }

    @Override
    public ViewCoreProcedureRecord value3(OffsetDateTime value) {
        setOperationDttm(value);
        return this;
    }

    @Override
    public ViewCoreProcedureRecord value4(Long value) {
        setStatusId(value);
        return this;
    }

    @Override
    public ViewCoreProcedureRecord value5(LocalDate value) {
        setStatusDt(value);
        return this;
    }

    @Override
    public ViewCoreProcedureRecord value6(Long value) {
        setCoreCaseId(value);
        return this;
    }

    @Override
    public ViewCoreProcedureRecord value7(String value) {
        setCreateUser(value);
        return this;
    }

    @Override
    public ViewCoreProcedureRecord value8(OffsetDateTime value) {
        setCreateDttm(value);
        return this;
    }

    @Override
    public ViewCoreProcedureRecord value9(OffsetDateTime value) {
        setModifyDttm(value);
        return this;
    }

    @Override
    public ViewCoreProcedureRecord value10(String value) {
        setActionInd(value);
        return this;
    }

    @Override
    public ViewCoreProcedureRecord values(Long value1, Long value2, OffsetDateTime value3, Long value4, LocalDate value5, Long value6, String value7, OffsetDateTime value8, OffsetDateTime value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewCoreProcedureRecord
     */
    public ViewCoreProcedureRecord() {
        super(ViewCoreProcedure.VIEW_CORE_PROCEDURE);
    }

    /**
     * Create a detached, initialised ViewCoreProcedureRecord
     */
    public ViewCoreProcedureRecord(Long coreProcedureId, Long operationId, OffsetDateTime operationDttm, Long statusId, LocalDate statusDt, Long coreCaseId, String createUser, OffsetDateTime createDttm, OffsetDateTime modifyDttm, String actionInd) {
        super(ViewCoreProcedure.VIEW_CORE_PROCEDURE);

        setCoreProcedureId(coreProcedureId);
        setOperationId(operationId);
        setOperationDttm(operationDttm);
        setStatusId(statusId);
        setStatusDt(statusDt);
        setCoreCaseId(coreCaseId);
        setCreateUser(createUser);
        setCreateDttm(createDttm);
        setModifyDttm(modifyDttm);
        setActionInd(actionInd);
        resetChangedOnNotNull();
    }
}
