/*
 * This file is generated by jOOQ.
 */
package dev.turbin.jooqtest.jooq.udt;


import dev.turbin.jooqtest.jooq.PassportInternational;
import dev.turbin.jooqtest.jooq.udt.records.CounterResultRecord;

import java.time.LocalDateTime;

import org.jooq.Schema;
import org.jooq.UDTField;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.SchemaImpl;
import org.jooq.impl.UDTImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CounterResult extends UDTImpl<CounterResultRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>passport_international.counter_result</code>
     */
    public static final CounterResult COUNTER_RESULT = new CounterResult();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CounterResultRecord> getRecordType() {
        return CounterResultRecord.class;
    }

    /**
     * The attribute
     * <code>passport_international.counter_result.core_counter_id</code>.
     */
    public static final UDTField<CounterResultRecord, Long> CORE_COUNTER_ID = createField(DSL.name("core_counter_id"), SQLDataType.BIGINT, COUNTER_RESULT, "");

    /**
     * The attribute
     * <code>passport_international.counter_result.department_code</code>.
     */
    public static final UDTField<CounterResultRecord, String> DEPARTMENT_CODE = createField(DSL.name("department_code"), SQLDataType.VARCHAR(128), COUNTER_RESULT, "");

    /**
     * The attribute
     * <code>passport_international.counter_result.region_code</code>.
     */
    public static final UDTField<CounterResultRecord, String> REGION_CODE = createField(DSL.name("region_code"), SQLDataType.VARCHAR(128), COUNTER_RESULT, "");

    /**
     * The attribute
     * <code>passport_international.counter_result.issue_year</code>.
     */
    public static final UDTField<CounterResultRecord, Integer> ISSUE_YEAR = createField(DSL.name("issue_year"), SQLDataType.INTEGER, COUNTER_RESULT, "");

    /**
     * The attribute
     * <code>passport_international.counter_result.operation_code</code>.
     */
    public static final UDTField<CounterResultRecord, String> OPERATION_CODE = createField(DSL.name("operation_code"), SQLDataType.VARCHAR(128), COUNTER_RESULT, "");

    /**
     * The attribute
     * <code>passport_international.counter_result.last_serial_num</code>.
     */
    public static final UDTField<CounterResultRecord, Long> LAST_SERIAL_NUM = createField(DSL.name("last_serial_num"), SQLDataType.BIGINT, COUNTER_RESULT, "");

    /**
     * The attribute
     * <code>passport_international.counter_result.create_dttm</code>.
     */
    public static final UDTField<CounterResultRecord, LocalDateTime> CREATE_DTTM = createField(DSL.name("create_dttm"), SQLDataType.LOCALDATETIME(0), COUNTER_RESULT, "");

    /**
     * The attribute
     * <code>passport_international.counter_result.modify_dttm</code>.
     */
    public static final UDTField<CounterResultRecord, LocalDateTime> MODIFY_DTTM = createField(DSL.name("modify_dttm"), SQLDataType.LOCALDATETIME(0), COUNTER_RESULT, "");

    /**
     * The attribute
     * <code>passport_international.counter_result.action_ind</code>.
     */
    public static final UDTField<CounterResultRecord, String> ACTION_IND = createField(DSL.name("action_ind"), SQLDataType.VARCHAR(1), COUNTER_RESULT, "");

    /**
     * No further instances allowed
     */
    private CounterResult() {
        super("counter_result", null, null, false);
    }

    @Override
    public Schema getSchema() {
        return PassportInternational.PASSPORT_INTERNATIONAL != null ? PassportInternational.PASSPORT_INTERNATIONAL : new SchemaImpl(DSL.name("passport_international"));
    }
}
