/*
 * This file is generated by jOOQ.
 */
package dev.turbin.jooqtest.jooq.tables;


import dev.turbin.jooqtest.jooq.Indexes;
import dev.turbin.jooqtest.jooq.Keys;
import dev.turbin.jooqtest.jooq.PassportInternational;
import dev.turbin.jooqtest.jooq.tables.records.CoreCommentAuditRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function11;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row11;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Таблица версионирования core_comment
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CoreCommentAudit extends TableImpl<CoreCommentAuditRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>passport_international.core_comment_audit</code>
     */
    public static final CoreCommentAudit CORE_COMMENT_AUDIT = new CoreCommentAudit();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CoreCommentAuditRecord> getRecordType() {
        return CoreCommentAuditRecord.class;
    }

    /**
     * The column <code>passport_international.core_comment_audit.id</code>.
     * Идентификатор
     */
    public final TableField<CoreCommentAuditRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "Идентификатор");

    /**
     * The column
     * <code>passport_international.core_comment_audit.record_id</code>.
     * Иденитификатор версионируемой записи
     */
    public final TableField<CoreCommentAuditRecord, Long> RECORD_ID = createField(DSL.name("record_id"), SQLDataType.BIGINT, this, "Иденитификатор версионируемой записи");

    /**
     * The column
     * <code>passport_international.core_comment_audit.correction_log_id</code>.
     * Идентификатор лога коррекции дела
     */
    public final TableField<CoreCommentAuditRecord, Long> CORRECTION_LOG_ID = createField(DSL.name("correction_log_id"), SQLDataType.BIGINT.nullable(false), this, "Идентификатор лога коррекции дела");

    /**
     * The column
     * <code>passport_international.core_comment_audit.update_user</code>.
     * Пользователь создавший версию
     */
    public final TableField<CoreCommentAuditRecord, String> UPDATE_USER = createField(DSL.name("update_user"), SQLDataType.VARCHAR, this, "Пользователь создавший версию");

    /**
     * The column
     * <code>passport_international.core_comment_audit.eff_dttm</code>. Время
     * начала действия версии effective from
     */
    public final TableField<CoreCommentAuditRecord, OffsetDateTime> EFF_DTTM = createField(DSL.name("eff_dttm"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("'1900-12-31 00:00:00'::timestamp without time zone"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "Время начала действия версии effective from");

    /**
     * The column
     * <code>passport_international.core_comment_audit.exp_dttm</code>. Время
     * окончания действия версии expired
     */
    public final TableField<CoreCommentAuditRecord, OffsetDateTime> EXP_DTTM = createField(DSL.name("exp_dttm"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("(now())::timestamp without time zone"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "Время окончания действия версии expired");

    /**
     * The column
     * <code>passport_international.core_comment_audit.core_case_id</code>.
     */
    public final TableField<CoreCommentAuditRecord, Long> CORE_CASE_ID = createField(DSL.name("core_case_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column
     * <code>passport_international.core_comment_audit.create_user</code>.
     */
    public final TableField<CoreCommentAuditRecord, String> CREATE_USER = createField(DSL.name("create_user"), SQLDataType.VARCHAR, this, "");

    /**
     * The column
     * <code>passport_international.core_comment_audit.comment_desc</code>.
     */
    public final TableField<CoreCommentAuditRecord, String> COMMENT_DESC = createField(DSL.name("comment_desc"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>passport_international.core_comment_audit.supplier_category_id</code>.
     */
    public final TableField<CoreCommentAuditRecord, Long> SUPPLIER_CATEGORY_ID = createField(DSL.name("supplier_category_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column
     * <code>passport_international.core_comment_audit.comment_type_id</code>.
     */
    public final TableField<CoreCommentAuditRecord, Long> COMMENT_TYPE_ID = createField(DSL.name("comment_type_id"), SQLDataType.BIGINT, this, "");

    private CoreCommentAudit(Name alias, Table<CoreCommentAuditRecord> aliased) {
        this(alias, aliased, null);
    }

    private CoreCommentAudit(Name alias, Table<CoreCommentAuditRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Таблица версионирования core_comment"), TableOptions.table());
    }

    /**
     * Create an aliased <code>passport_international.core_comment_audit</code>
     * table reference
     */
    public CoreCommentAudit(String alias) {
        this(DSL.name(alias), CORE_COMMENT_AUDIT);
    }

    /**
     * Create an aliased <code>passport_international.core_comment_audit</code>
     * table reference
     */
    public CoreCommentAudit(Name alias) {
        this(alias, CORE_COMMENT_AUDIT);
    }

    /**
     * Create a <code>passport_international.core_comment_audit</code> table
     * reference
     */
    public CoreCommentAudit() {
        this(DSL.name("core_comment_audit"), null);
    }

    public <O extends Record> CoreCommentAudit(Table<O> child, ForeignKey<O, CoreCommentAuditRecord> key) {
        super(child, key, CORE_COMMENT_AUDIT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : PassportInternational.PASSPORT_INTERNATIONAL;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.CORE_COMMENT_AUDIT_CORRECTION_LOG_IX, Indexes.CORE_COMMENT_AUDIT_EFF_DTTM_IX, Indexes.CORE_COMMENT_AUDIT_RECORD_ID_IX);
    }

    @Override
    public Identity<CoreCommentAuditRecord, Long> getIdentity() {
        return (Identity<CoreCommentAuditRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<CoreCommentAuditRecord> getPrimaryKey() {
        return Keys.CORE_COMMENT_AUDIT_PK;
    }

    @Override
    public List<ForeignKey<CoreCommentAuditRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CORE_COMMENT_AUDIT__CORE_COMMENT_AUDIT_FK, Keys.CORE_COMMENT_AUDIT__CORE_COMMENT_AUDIT_CORRECTION_LOG_FK);
    }

    private transient CoreComment _coreComment;
    private transient CorrectionLog _correctionLog;

    /**
     * Get the implicit join path to the
     * <code>passport_international.core_comment</code> table.
     */
    public CoreComment coreComment() {
        if (_coreComment == null)
            _coreComment = new CoreComment(this, Keys.CORE_COMMENT_AUDIT__CORE_COMMENT_AUDIT_FK);

        return _coreComment;
    }

    /**
     * Get the implicit join path to the
     * <code>passport_international.correction_log</code> table.
     */
    public CorrectionLog correctionLog() {
        if (_correctionLog == null)
            _correctionLog = new CorrectionLog(this, Keys.CORE_COMMENT_AUDIT__CORE_COMMENT_AUDIT_CORRECTION_LOG_FK);

        return _correctionLog;
    }

    @Override
    public CoreCommentAudit as(String alias) {
        return new CoreCommentAudit(DSL.name(alias), this);
    }

    @Override
    public CoreCommentAudit as(Name alias) {
        return new CoreCommentAudit(alias, this);
    }

    @Override
    public CoreCommentAudit as(Table<?> alias) {
        return new CoreCommentAudit(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CoreCommentAudit rename(String name) {
        return new CoreCommentAudit(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CoreCommentAudit rename(Name name) {
        return new CoreCommentAudit(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CoreCommentAudit rename(Table<?> name) {
        return new CoreCommentAudit(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, Long, Long, String, OffsetDateTime, OffsetDateTime, Long, String, String, Long, Long> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function11<? super Long, ? super Long, ? super Long, ? super String, ? super OffsetDateTime, ? super OffsetDateTime, ? super Long, ? super String, ? super String, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function11<? super Long, ? super Long, ? super Long, ? super String, ? super OffsetDateTime, ? super OffsetDateTime, ? super Long, ? super String, ? super String, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
